# Generated by Django 3.2 on 2021-04-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
