# Generated by Django 3.2 on 2021-04-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210420_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customers',
            new_name='customer',
        ),
    ]
